### ISSUE TITLE
Flag SubCommands in YAML?

### ISSUE THREAD

**Issue by epage** [epage/clapng#236]
<a href="https://github.com/epage"><img src="https://avatars.githubusercontent.com/u/60961?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [epage](https://github.com/epage)**
_Tuesday Nov 09, 2021 at 16:18 GMT_
_Originally opened as https://github.com/clap-rs/clap/issues/3011_

----

### Discussed in https://github.com/clap-rs/clap/discussions/3010

<div type='discussions-op-text'>

<sup>Originally posted by **Kibouo** November  9, 2021</sup>
I saw that #1974 added support for sub-commands with a flag-format. However, they don't seem to be available when ingesting YAML?

I tried the following:
```yaml
[...]
subcommands:
    - web:
        about: "web subcommand"
        short_flag: W
        long_flag: web
[...]
```

However, the keys `short_flag` and `long_flag` are silently ignored. Meaning, `cargo run -- --help` shows only `web` as a sub-command.

I expected it to show `-W, --web, web`.</div>
