### ISSUE TITLE
Support or document localization of messages and flags

### ISSUE THREAD

**Issue by epage** [epage/clapng#63]
<a href="https://github.com/kamalmarhubi"><img src="https://avatars.githubusercontent.com/u/50936?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kamalmarhubi](https://github.com/kamalmarhubi)**
_Tuesday Jan 12, 2016 at 16:57 GMT_
_Originally opened as https://github.com/clap-rs/clap/issues/380_

----

Make it easy for developers to support translations of their projects.

**Comment by epage** [comment]
<a href="https://github.com/kbknapp"><img src="https://avatars.githubusercontent.com/u/6942134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbknapp](https://github.com/kbknapp)**
_Wednesday Jan 13, 2016 at 07:10 GMT_

----

This is something I'm interested in doing, but it will take some thought on how to best go about this. I'm putting it on the issue tracker, but let's get some discussion going on ways about this!

**Comment by epage** [comment]
<a href="https://github.com/kbknapp"><img src="https://avatars.githubusercontent.com/u/6942134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbknapp](https://github.com/kbknapp)**
_Monday Jan 25, 2016 at 15:05 GMT_

----

@kamalmarhubi I was thinking about this today, and would the YAML feature allow this? I.e. I'm thinking having a differente yaml file for each translation, and depending on which language/translation is compiled via features, you pick a different yaml file.

Example:

``` toml
# Cargo.toml

[features]
default = ["en_US"]
en_US = []
es_ES = []
```

``` yaml
# en_US.yml
name: My Application
version: 1.0
about: An example using many languages
author: Kevin K. <kbknapp@gmail.com>
args:
    - opt:
        help: an example option
        short: o
        long: option
        multiple: true
        takes_value: true
    - pos:
        help: example positional with possible values
        index: 1
        possible_values:
            - fast
            - slow
```

``` yaml
# es_ES.yml
name: Mi Aplicacion
version: 1.0
about: Un ejamlo util muy idiomas
author: Kevin K. <kbknapp@gmail.com>
args:
    - opt:
        help: un ejamplo de un opcion
        short: o
        long: opcion
        multiple: true
        takes_value: true
    - pos:
        help: un ejamplo de un posicion con valores posible
        index: 1
        possible_values:
            - rapido
            - lento
```

``` rust
// main.rs
#[cfg(feature = "en_US")]
const TRANSLATION: &'static str = "en_US.yml";

#[cfg(feature = "es_ES"]
const TRANSLATION: &'static str = "es_ES.yml";

fn main() {
    let yml = load_yaml!(TRANSLATION);
    let m = App::from_yaml(yml).get_matches();
}
```

Then depending on if you compile with `--features en_US` or `--features es_ES` it will set the translation. Does this work for you?
